=== S200124/Assignment1b/dtd/wfInfo.dtd
<!ELEMENT wfInfo (workflow+)>

<!ELEMENT workflow (action+, process+) >
<!ATTLIST workflow
		name	CDATA	#REQUIRED
>

<!ELEMENT action (role, (followingActions | nestedWorkflow)?) >
<!ATTLIST action
		name		CDATA			#REQUIRED
		type		(simple | process)	#REQUIRED
		automInst	(true | false)		#REQUIRED
>

<!ELEMENT actor (role) >
<!ATTLIST actor
		name	CDATA	#REQUIRED
>

<!ELEMENT role (#PCDATA) >

<!ELEMENT followingActions (actionName+) >

<!ELEMENT actionName (#PCDATA) >

<!ELEMENT nestedWorkflow EMPTY >
<!ATTLIST nestedWorkflow
		workflowName	CDATA		#REQUIRED
>

<!ELEMENT process (actionStatus+) >
<!ATTLIST process
		startAt		CDATA	#REQUIRED
>

<!ELEMENT actionStatus (actionName, actor?) >
<!ATTLIST actionStatus
		terminatedAt	CDATA	#IMPLIED
>

=== S200124/Assignment1b/dtd/file.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE wfInfo SYSTEM "wfInfo.dtd">
<wfInfo><workflow name="ArticleProduction"><action automInst="false" name="Checking" type="simple"><role>Editor</role><followingActions><actionName>Revising</actionName><actionName>Publication</actionName></followingActions></action><action automInst="false" name="Publication" type="simple"><role>Editor</role></action><action automInst="false" name="Revising" type="simple"><role>Journalist</role><followingActions><actionName>Checking</actionName></followingActions></action><action automInst="true" name="Writing" type="simple"><role>Journalist</role><followingActions><actionName>Checking</actionName></followingActions></action></workflow><process startAt="Mon Oct 05 12:31:40 CEST 2015" workflowName="ArticleProduction"><actionStatus><actor name="Paolo Menegai"><role>Journalist</role></actor><actionName>Writing</actionName></actionStatus></process><process startAt="Mon Oct 12 17:53:40 CEST 2015" workflowName="ArticleProduction"><actionStatus terminatedAt="1444828300000"><actor name="Paolo Menegai"><role>Journalist</role></actor><actionName>Writing</actionName></actionStatus><actionStatus terminatedAt="1444831060000"><actor name="Betty La Viola"><role>Editor</role></actor><actionName>Checking</actionName></actionStatus><actionStatus terminatedAt="1444943140000"><actor name="Ludovico Del Saio"><role>Journalist</role></actor><actionName>Revising</actionName></actionStatus><actionStatus><actionName>Checking</actionName></actionStatus></process><process startAt="Thu Oct 08 07:53:40 CEST 2015" workflowName="ArticleProduction"><actionStatus terminatedAt="1444343020000"><actor name="Anreina Perla"><role>Journalist</role></actor><actionName>Writing</actionName></actionStatus><actionStatus terminatedAt="1444513780000"><actor name="Anreina Li Ming"><role>Editor</role></actor><actionName>Checking</actionName></actionStatus><actionStatus><actor name="Anreina Piceni"><role>Editor</role></actor><actionName>Publication</actionName></actionStatus></process><process startAt="Fri Oct 09 20:45:40 CEST 2015" workflowName="ArticleProduction"><actionStatus terminatedAt="1444587100000"><actor name="Anreina Perla"><role>Journalist</role></actor><actionName>Writing</actionName></actionStatus><actionStatus terminatedAt="1444612360000"><actor name="Anreina Piceni"><role>Editor</role></actor><actionName>Checking</actionName></actionStatus><actionStatus terminatedAt="1444775980000"><actor name="Paolo Menegai"><role>Journalist</role></actor><actionName>Revising</actionName></actionStatus><actionStatus terminatedAt="1444883080000"><actor name="Anreina Piceni"><role>Editor</role></actor><actionName>Checking</actionName></actionStatus><actionStatus><actor name="Anreina Piceni"><role>Editor</role></actor><actionName>Publication</actionName></actionStatus></process><process startAt="Fri Oct 16 13:05:40 CEST 2015" workflowName="ArticleProduction"><actionStatus terminatedAt="1445076880000"><actor name="Ludovico Del Saio"><role>Journalist</role></actor><actionName>Writing</actionName></actionStatus><actionStatus><actor name="Anreina Li Ming"><role>Editor</role></actor><actionName>Checking</actionName></actionStatus></process><process startAt="Tue Oct 06 10:41:40 CEST 2015" workflowName="ArticleProduction"><actionStatus terminatedAt="1444213360000"><actor name="Anreina Perla"><role>Journalist</role></actor><actionName>Writing</actionName></actionStatus><actionStatus terminatedAt="1444308520000"><actor name="Anreina Li Ming"><role>Editor</role></actor><actionName>Checking</actionName></actionStatus><actionStatus><actionName>Publication</actionName></actionStatus></process><process startAt="Thu Oct 15 08:50:40 CEST 2015" workflowName="ArticleProduction"><actionStatus><actionName>Writing</actionName></actionStatus></process></wfInfo>
